### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by electrickite** [pop-os/system76-firmware#14]
Would it be possible to tag a new version of system76-firmware? The current version (1.0.4) will not build on Rust stable releases.

**Comment by mmstick** [comment]
> The current version (1.0.4) will not build on Rust stable releases.

Our Jenkins CI / CD scripts won't pass a commit if the project is unable to build debian packages in a clean schroot with the version of rustc in the bionic, cosmic, and disco Ubuntu repositories. Currently, that version is 1.31.0. Latest stable version is 1.34.0.

**Comment by electrickite** [comment]
The latest commit compiles on rust 1.34.1 stable, but the last tagged release, 1.0.4, does not.

Latest commit to master:

```
$ rustc --version
rustc 1.34.1
$ git clone https://github.com/pop-os/system76-firmware.git
Cloning into 'system76-firmware'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 284 (delta 32), reused 50 (delta 20), pack-reused 220
Receiving objects: 100% (284/284), 129.91 KiB | 2.45 MiB/s, done.
Resolving deltas: 100% (156/156), done.
$ git branch
* master
$ git log --pretty=format:'%h' -n 1
edaf4c5
$ cd system76-firmware/
$ make
if [ -d vendor ]; \
then \
	cargo build --release --frozen; \
else \
	cargo build --release; \
fi
   Compiling semver-parser v0.7.0
   ...
   Compiling system76-firmware v1.0.4 (/home/corey/system76-firmware)
    Finished release [optimized] target(s) in 3m 25s
```

And the 1.0.4 tag:

```
$ git checkout 1.0.4
Note: checking out '1.0.4'.
HEAD is now at 42e2d59 1.0.4 - update public key
$ make
if [ -d vendor ]; \
then \
	cargo build --release --frozen; \
else \
	cargo build --release; \
fi
   Compiling semver-parser v0.7.0
   ...
   Compiling rand_core v0.3.1
error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/corey/.cargo/registry/src/github.com-1ecc6299db9ec823/system76_ecflash-0.1.0/src/lib.rs:2:1
  |
2 | #![feature(alloc)]
  | ^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/corey/.cargo/registry/src/github.com-1ecc6299db9ec823/system76_ecflash-0.1.0/src/lib.rs:3:1
  |
3 | #![feature(asm)]
  | ^^^^^^^^^^^^^^^^

   Compiling rand_jitter v0.1.3
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `system76_ecflash`.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:56: target/release/system76-firmware-cli] Error 101
```

It seems to fail because ecflash 0.1.0 uses an unstable #![feature] flag which rust stable will not compile.

**Comment by jackpot51** [comment]
1.0.5 was released.
